---
- name: Ensures /etc/my.cnf.d dir exists
  file: path=/etc/my.cnf.d/ state=directory
  tags:
  - root-task

- name: Configure MariaDB
  template:
    src: mysql.cnf
    dest: /etc/my.cnf.d/mysql.cnf
  tags:
  - root-task

- name: Install MariaDB server package
  package:
    name: mariadb-server
    state: present
  tags:
  - packages
  - root-task

- name: Start Mysql Service
  service:
    name: mysql
    state: started
    enabled: true
  tags:
  - root-task
