---
- name: Ensure mysql python packages are present
  package:
    name: python-mysqldb
  become: yes
  tags:
  - packages
  - root-task

- name: Remove existing database with name 'esrender'
  mysql_db:
    name: '{{esrender_db.name}}'
    state: absent
  become: yes
  when: esrender_remove_existing
  tags:
  - root-task

- name: Create a new database with name 'esrender'
  mysql_db:
    name: '{{esrender_db.name}}'
    config_file: /etc/my.cnf.d/mysql.cnf
    state: present
  become: yes
  tags:
  - root-task

- name: Create esrender database user
  mysql_user:
    name: '{{esrender_db.user}}'
    password: '{{esrender_db.password}}'
    priv: '{{esrender_db.name}}.*:ALL'
  become: yes
  tags:
  - root-task
