---
- name: download mysql jconnector (mariadb driver not supported by alfresco)
  get_url:
    url: '{{mysql_jconnector_url}}'
    dest: "{{tomcat_home}}/lib/mysql-connector-java.jar"
    force: yes # necessary for driver updates
  when: alfresco_db_type == 'mariadb'

- name: download postgres jconnector
  get_url:
    url: '{{postgresql_jconnector_url}}'
    dest: "{{tomcat_home}}/lib/postgresql.jar"
    force: yes # necessary for driver updates
  when: alfresco_db_type == 'postgresql'

- name: download alfresco sources
  get_url:
    url: '{{alf_sources_url}}'
    dest: "{{alf_inst_dir}}/{{alf_name}}.zip"

- name: Ensure unzip is present
  package:
    name: ["unzip"]
  become: yes
  tags:
  - packages
  - root-task

- name: extract alfresco sources
  unarchive:
    remote_src: yes
    src: '{{alf_inst_dir}}/{{alf_name}}.zip'
    dest: "{{alf_inst_dir}}"
    creates: "{{alf_home}}"

- name: stop alfresco
  shell: '{{tomcat_stop_command}}'
  tags: edu-sharing-config

- name: undeploy alresco war-files from tomcat
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - "{{tomcat_home}}/webapps/alfresco.war"
    - "{{tomcat_home}}/webapps/alfresco"
    - "{{tomcat_home}}/work/Catalina/localhost/alfresco"
    - "{{tomcat_home}}/webapps/share.war"
    - "{{tomcat_home}}/webapps/share"
    - "{{tomcat_home}}/work/Catalina/localhost/share"

- name: copy alfresco war-files to tomcat
  copy:
    src: "{{item}}"
    dest: "{{tomcat_home}}/webapps"
    remote_src: yes
  with_items:
    - "{{alf_home}}/web-server/webapps/alfresco.war"
    - "{{alf_home}}/web-server/webapps/share.war"

- name: Ensures {{tomcat_home}}/shared dir exists
  file: path={{tomcat_home}}/shared/ state=directory

- name: copy alresco default tomcat config
  copy:
    src: "{{alf_home}}/web-server/shared/classes"
    dest: "{{tomcat_home}}/shared/"
    remote_src: yes

- name: activate shared.loader for tomcat
  lineinfile:
    path: '{{ tomcat_home }}/conf/catalina.properties'
    line: 'shared.loader=${catalina.base}/shared/classes'
    regexp: 'shared.loader='

- name: set javax.xml properties
  lineinfile:
    path: '{{ tomcat_home }}/conf/catalina.properties'
    line: '{{item[0]}}={{item[1]}}'
    regexp: '{{item[0]}}='
  loop:
    - ["javax.xml.parsers.DocumentBuilderFactory", 'com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl']
    - ["javax.xml.transform.TransformerFactory", 'com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl']
    - ["javax.xml.parsers.SAXParserFactory", 'com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl']
    - ["javax.xml.datatype.DatatypeFactory", 'com.sun.org.apache.xerces.internal.jaxp.datatype.DatatypeFactoryImpl']

- name: Configure alfresco-global.properties
  template:
    src: alfresco-global.properties.j2
    dest: '{{tomcat_home}}/shared/classes/alfresco-global.properties'
  tags: edu-sharing-config

- name: Ensure python-lxml packages are present
  apt:
    name: ["python-lxml"]
  become: yes
  tags:
  - packages
  - root-task

- name: modify tomcat config - allow only local access
  xml:
    path: '{{tomcat_home}}/conf/server.xml'
    xpath: /Server/Service/Connector
    attribute: address
    value: 127.0.0.1
  tags: edu-sharing-config
