---

- name: adjustments of the edu-sharing alfresco extension models
  xml:
    path: '{{ tomcat_home }}/shared/classes/alfresco/extension/{{item.path}}'
    xpath: '{{ item.xpath }}'
    value: '{{ item.value }}'
    namespaces:
      ns: http://www.alfresco.org/model/dictionary/1.0
    pretty_print: yes
  loop: '{{ edu_cccontentmodel_adjustments | default([], true) }}'


- name: Add custom property in alfresco extension models
  xml:
    path: '{{ tomcat_home }}/shared/classes/alfresco/extension/{{item.path}}'
    xpath: '{{ item.xpath }}'
    add_children: '{{ item.properties }}'
    input_type: xml
    # with_items: '{{ item.children }}'
    namespaces:
      ns: http://www.alfresco.org/model/dictionary/1.0
    pretty_print: yes   
  with_items: '{{ alfresco_ccmodel_add_custom_properties | default([], true) }}'
  when: (alfresco_ccmodel_add_custom_properties != "") and (alfresco_ccmodel_add_custom_properties is not none)
